DROP TABLE IF EXISTS card_data;
DROP TABLE IF EXISTS binary_data;
DROP TABLE IF EXISTS text_data;
DROP TABLE IF EXISTS login_data;
DROP TABLE IF EXISTS user_data;
DROP TABLE IF EXISTS data_types;
DROP TABLE IF EXISTS users;
